gifsong/urls.py
from django.conf.urls import patterns, include, url

from gifsong.views import addgifsong, showgifsong

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gifsong.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')) 
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^addgifsong/', addgifsong.as_view(), name='AddGifSong'),
    url(r'^show/', showgifsong.as_view(), name='ShowGifSong'),
    url(r'^$', addgifsong.as_view(), name='home'),
)

gifsong/models.py
from django.db import models

class SFWManager(models.Manager):
    def get_queryset(self):
        return super(SFWManager, self).get_queryset().filter(sfwness=gifsong.SFW)

class gifsong(models.Model):
    SFW = 1
    NSFW = 2
    UNKNOWN = 3
    STATUS_CHOICES = (
        (SFW, 'SFW'),
        (NSFW, 'NSFW'),
        (UNKNOWN, 'Unknown'),
    )

    image_url = models.CharField(max_length=255)
    audio_url = models.CharField(max_length=255)
    sfwness = models.PositiveIntegerField(choices=STATUS_CHOICES, default=UNKNOWN)

    objects = models.Manager()
    sfw = SFWManager()

    def create(cls, image_url, audio_url):
        gifsong = cls()
        return gifsong

gifsong/views.py
#! /usr/bin/env python2.7
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.forms import ModelForm
from django.db.models import Q

from gifsong.models import gifsong

class GifSongForm(ModelForm):
    class Meta:
        model = gifsong
        fields = ['image_url', 'audio_url']

class showgifsong(TemplateView):
    template_name = 'showsong.html'

    def get(self, request, *args, **kwargs):
        gvidid = request.GET.get('gvid')
        nsfw = request.GET.get('nsfw')
        agifsong = None

        if(gvidid):
            agifsong = gifsong.objects.get(id=gvidid)

        if (agifsong == None):
            if(nsfw == None):
                sfw = gifsong.objects.all().filter(Q(sfwness=1) | Q(sfwness=3)).order_by('?')
                if(sfw):
                    agifsong = sfw[0]
            if(nsfw):
                agifsong = gifsong.objects.order_by('?')[0]

        context = {
            'song' : agifsong,
        }

        return self.render_to_response(context)

class addgifsong(TemplateView):
    template_name = 'createsong.html'

    def get(self, request, *args, **kwargs):

        form = GifSongForm()

        context = {
            'form' : form,
        }

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = GifSongForm(request.POST)
        if form.is_valid():
            song = form.save()
            return redirect('/show?gvid=' + str(song.id))

        return self.render_to_response({'form': GifSongForm() })

gifsong/templates/base.html
{% load googleanalytics_tags %}
<html>
<head>
    <title>gifsong</title>
    <!-- cdn -->
    <!-- css -->
    <link href='http://fonts.googleapis.com/css?family=Duru+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://yui.yahooapis.com/3.14.1/build/cssbutton/cssbutton.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <!-- js -->
    {% googleanalytics %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!-- gifsong -->
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/animate.css">
    {% block css_override_block %}{% endblock %}
</head>
<body>
   {% block override_block %}{% endblock %}
   {% block container %}{% endblock %}
</body>
</html>

gifsong/templates/createsong.html
{% extends "base.html" %}

{% block css_override_block %}
    <script src="{{ STATIC_URL }}js/jquery.steps.min.js"></script>
    <script src="{{ STATIC_URL }}js/SwfObject.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.steps.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/createsong.css">
{% endblock %}

{% block override_block %}
    <div id="sharebar">&nbsp;
        <a class="yui3-button fa fa-home"me  href="/"> GIFSong</a>
        <a class="yui3-button fa fa-random"  href="/show"> random</a>
    </div>
{% endblock %}

{% block container %}
{% include "includes/github.html" %}
<form action="/" method="post">
    {{ form.non_field_errors }}
    {% csrf_token %}
<div id="wizard">
                <h2>GIF Url</h2>
                <section>
                    <div class="fieldWrapper">
                        {{ form.image_url.errors }}
                        {{ form.image_url }}
                    </div>
                </section>

                <h2>Youtube Url</h2>
                <section>
                    <div class="fieldWrapper">
                        {{ form.audio_url.errors }}
                        {{ form.audio_url }}
                    </div>
                </section>

                <h2>Create</h2>
                <section>
                    <input id="submitgifvid" class="yui3-button success" type="submit" value="Create" />

                </section>
            </div>
</form>
<div id="previewSong"></div>
    <script>
     // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var previewSong;
    $(function(){
        $("#id_image_url").attr("placeholder","http://i.imgur.com/WJBkMZ1.gif");
        $("#id_audio_url").attr("placeholder","http://youtu.be/6M5SflJgsQ0");

        $("#id_image_url").change(function(){
             alert('error');
            $("<img>", {
                    src: $("#id_image_url").val(),
                    error: function() { alert('error'); },
                    load: function() { },
            });
         });

        var imageError = false;

        $("#wizard").steps({
            headerTag: "h2",
            bodyTag: "section",
            transitionEffect: "slideLeft",
            height:"200",
            enableFinishButton: false,
            onStepChanging: function (event, currentIndex, newIndex) {
                if(currentIndex == 0){
                    var previewFix = "http://";
                    if ($("#id_image_url").val().indexOf("http://")==0 || $("#id_image_url").val().indexOf("https://")==0) {
                        var val = $("#id_image_url").val().replace("http://","");
                        val = val.replace("https://","");
                        $("#id_image_url").val(val);
                        console.log(val);
                    }
                    $("<img>", {
                        src: previewFix + $("#id_image_url").val(),
                        error: function() { $('li.first').addClass('error');  $("#submitgifvid").attr("disabled", "disabled");},
                        load: function() {
                                console.log('loafef');
                                $('li.first').removeClass('error');
                                $("html").css('background','url(' + previewFix + $("#id_image_url").val() +') no-repeat center center fixed');
                                $("html").css('-webkit-background-size', 'cover');
                                $("html").css('-moz-background-size', 'cover');
                                $("html").css('-o-background-size', 'cover');
                                $("html").css('background-size:', 'cover');
                                $("#submitgifvid").removeAttr("disabled");
                        },
                    });
                }

                if(currentIndex == 1){

                    var tubeid = getTubeId($("#id_audio_url").val());



                    $("#previewSong").remove();
                    $("body").append(
                    $('<div></div>', {id:"previewSong"})

                    );

                     $("#previewSong").css('display', 'none');
                      // 3. This function creates an <iframe> (and YouTube player)
                      //    after the API code downloads.

                        previewSong = new YT.Player('previewSong', {
                          height: '200',
                          width: '200',
                          videoId: tubeid,
                          playerVars: { 'autoplay': 1 },
                          events: {
                            'onReady': function(event){console.log('ready', event);
                                    if (previewSong.getDuration() <= 0){
                                        //error
                                         $('ul li:eq(1)').addClass('error');
                                         $("#submitgifvid").attr("disabled", "disabled");
                                         $("#previewSong").remove();
                                    } else{
                                        $("#submitgifvid").removeAttr("disabled");
                                        $("#previewSong").css('display', 'block');
                                    }

                        console.log(previewSong.getDuration());




                                                      },
                            'onStateChange': function(){},
                            'onError': function(event){
                                console.log('error', event)
                             }
                          }
                        });



                }


                return true;
            },
        });

        function getTubeId(url){
                var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
                var match = url.match(regExp);
                if (match&&match[2].length==11){
                    console.log(match[2]);
                    return match[2];
                }else{
                    return false;
                }
        }





    });
    </script>
<style>
    body{
        margin:0;
    }
    #sharebar {
    position: relative;
    width: 100%;
    height: 2.5em;
    background-color: transparent;
    padding-top: 5px;
        text-align:left;
    font-size: 0.8em;
}


#sharebar a {
    color: #000;
    font-weight: bold;
}

.wizard > .content {
        background-color:transparent;
    }

.wizard > .steps > ul > li, .wizard > .actions > ul > li {
float: left;
opacity: .7;
}
    #id_audio_url::-webkit-input-placeholder, #id_image_url::-webkit-input-placeholder { /* WebKit browsers */
    color:    #333;
}
#id_image_url:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
    color:    #333;
}
#id_image_url::-moz-placeholder { /* Mozilla Firefox 19+ */
    color:    #333;
}
#id_image_url:-ms-input-placeholder { /* Internet Explorer 10+ */
    color:    #333;
}


#previewSong{
    position: absolute;
    bottom: 0;
    left: 0;
        display:block;
}

.wizard, .tabcontrol {
    display: block;
    width: 65%;
    overflow: hidden;
    margin-left: auto;
    margin-right: auto;
}
</style>
<div class="footer">
    <div class="copyright">Brought to you by these Doges.</div>
    <div class="doges clearfix">
        <a class="circular derek"  href="https://github.com/toxigenicpoem" target="_blank"></a>
        <a class="circular derick"  href="https://github.com/ZephyrXero" target="_blank"></a>
        <a class="circular burns"  href="https://github.com/nthdegreeburns" target="_blank"></a>
        <a class="circular justin"  href="https://github.com/bigjust" target="_blank"></a>
        <a class="circular mannyu"  href="https://github.com/mannyblum" target="_blank"></a>
        <a class="circular matt" href="https://github.com/mlsimpson" target="_blank"></a>
        <a class="circular nolan" href="https://github.com/nrb" target="_blank"></a>
    </div>
    <div class="copyright">Copyright &copy; 2014 Nintendoges</div>
</div>
{% endblock %}

gifsong/templates/includes/github.html
<a id="githubLink" href="https://github.com/toxigenicpoem/gifsong"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png" alt="Fork me on GitHub"></a>

gifsong/templates/includes/sharebar.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div id="sharebar">&nbsp;
    <a id="permaLink" data-show="" class="yui3-button fa fa-link" href="#"> perma link</a>
    <input id="permaLinkText" class="displayNone" value="http://www.gifsong.me/show?gvid={{song.id}}"/>
    <a class="yui3-button fa fa-plus-square" href="/"> create</a>
    <a class="yui3-button fa fa-random"  href="/show"> random</a>
    <a id="hideplayerButton" class="yui3-button fa fa-eye-slash"> Show Audio Player</a>
    <div class="fb-share-button" data-href="http://www.gifsong.me/show/?gvid={{song.id}}" data-type="button"></div>
</div>

gifsong/templates/showsong.html
{% extends "base.html" %}
{% block override_block %}
    {% include "includes/sharebar.html" %}
{% endblock %}
{% block css_override_block %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/showsong.css">
    <script src="https://www.youtube.com/iframe_api"></script>
    <!-- open graph tags -->
    <meta property="og:image" content="http://{{ song.image_url }}"/>
    <meta property="og:title" content="An Animated Jam"/>
    <meta property="og:url" content="http://www.gifsong.me/show/?gvid={{song.id}}"/>
    <meta property="og:site_name" content="GifSong.ME"/>
    <meta property="og:type" content="website"/>

{% endblock %}
{% block container %}
<style>
    html {
        background: url(http://{{ song.image_url }}) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    .displayNone {
        display:none !important;
    }
</style>

<div id="youtube" class="displayNone"></div>
<script>

//this code is duped, whateve, get it out of here if this is a money maker, rigggght
var youtube;
function getTubeId(url) {
    var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    var match = url.match(regExp);
    if (match && match[2].length == 11) {
        console.log(match[2]);
        return match[2];
    } else {
        return false;
    }
}

// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

function onYouTubeIframeAPIReady() {
    var tubeid = getTubeId("{{ song.audio_url }}");
    console.log(tubeid);
    youtube = new YT.Player('youtube', {
        height: '200',
        width: '200',
        videoId: tubeid,
        playerVars: {
            'autoplay': 1,
            'loop' : 1
        },
        events: {
            'onReady': function (event) {},
            'onStateChange': function (state) {
                if(state.data == 0){
                    youtube.playVideo();
                }
            },
            'onError': function (event) {}
        }
    });
}

$(function () {
    var i = setTimeout('$("#sharebar").removeClass();$("#sharebar").addClass("animated fadeOutUp");$("#githubLink").removeClass();', 2000);

    $("#permaLink").click(function (e) {
        var inout = "fade" + (($(this).attr("data-show").indexOf("Hide") > -1) ? "Out" : "In") + (($(this).text().indexOf("Hide") > -1) ? "Up" : "Down");
        $('#permaLinkText').removeClass();
        $("#permaLinkText").addClass('animated ' + inout);
        if (inout.indexOf("Out") > -1) {
            $("#permaLinkText").addClass('displayNone');
        }
        $(this).attr("data-show", function () {
            return (($(this).attr("data-show").indexOf("Hide") > -1) ? "Show" : "Hide");
        })
        e.preventDefault();
    });
    $("#hideplayerButton").click(function () {
        var inout = "fade" + (($(this).text().indexOf("Hide") > -1) ? "Out" : "In") + (($(this).text().indexOf("Hide") > -1) ? "Down" : "Up");
        $('#youtube').removeClass();
        $('#youtube').addClass('animated ' + inout);
        $(this).text(function () {
            return (($(this).text().indexOf("Hide") > -1) ? " Show" : " Hide") + " Audio Player";
        });
    });

    $("html").mousemove(function () {
        clearTimeout(i);
        $("#sharebar").removeClass();
        $("#githubLink").removeClass();
        $("#rating").removeClass();

        var inout = "fade" + (($(this).text().indexOf("Hide") > -1) ? "Out" : "In") + (($(this).text().indexOf("Hide") > -1) ? "Up" : "Down");
        var inoutOther = "fade" + (($(this).text().indexOf("Hide") > -1) ? "Out" : "In") + (($(this).text().indexOf("Hide") > -1) ? "Up" : "Down");
        i = setTimeout('$("#sharebar").removeClass();$("#sharebar").addClass("animated ' + inout + '");$("#githubLink").removeClass();$("#githubLink").addClass("animated ' + inoutOther + '");', 2000);
    });
});
</script>
{% endblock %}